/**
 * Created by alexanderbol on 27/12/2015.
 */

export const OPEN_IMPORT_FILES_POPUP = 'OPEN_IMPORT_FILES_POPUP';
export const CLOSE_IMPORT_FILES_POPUP = 'CLOSE_IMPORT_FILES_POPUP';
export const OPEN_DOWNLOAD_FILES_POPUP = 'OPEN_DOWNLOAD_FILES_POPUP';
export const CLOSE_DOWNLOAD_FILES_POPUP = 'CLOSE_DOWNLOAD_FILES_POPUP';
export const FETCH_LOCALE_SUCCEED = 'FETCH_LOCALE_SUCCEED';
export const FETCH_LANGUAGES_SUCCEED = 'FETCH_LANGUAGES_SUCCEED';
